### Recuperar todas las peliculas
GET http://localhost:3000/movies

### Recuperar pelicula por id
GET http://localhost:3000/movies/1

### Recuperar pelicula por id (base de datos)
GET http://localhost:3000/movies/6ca768ab-6ab6-11ee-99b0-285471c5be6c

### Recuperar todas las peliculas de un genero
GET http://localhost:3000/movies?genre=Terror

### Postear pelicula
POST http://localhost:3000/movies
Content-Type: application/json
{
		"title": "Propuesta Laboral",
    "genre": ["Drama"],
    "year": 2023,
    "director": "Desconocido",
    "duration": 200,
    "poster": "https://noimage.png"
}

### Actualizar una pelicula por id 
PATCH http://localhost:3000/movies/a7f71626-7585-11ee-99b0-285471c5be6c
Content-Type: application/json
{
		"title": "Propuesta Laboral",
    "genre": ["Drama"],
    "year": 2020,
    "director": "Coreanos",
    "duration": 500,
    "poster": "https://noimage.png"
}

### Borrar pelicula por id 
DELETE http://localhost:3000/movies/a7f71626-7585-11ee-99b0-285471c5be6c